name: Auto Draw ZMK keymaps
on:
  workflow_dispatch: # Allows you to run it manually from the Actions tab
  push:
    branches:
      - qwerty # Restricts auto-runs specifically to your main and qwerty branch
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - "keymap_drawer.config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write # Crucial: Allows the bot to commit the SVG back to your repo
    with:
      install_args: "" # Skip extra pip packages if not using zmk-helpers
      keymap_patterns: "config/*.keymap"
      output_folder: "keymap-drawer" # Saves diagrams inside a 'keymap-drawer' folder

